import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame,validateGame } from '../src/game/engine';
import { startLife,chooseLife,advanceLife,lifeAction,advanceLifePlan,familyOperation,economicOperation,medicalOperation,trade,adjustMargin,applyJob,die,inheritLife,lifeAge } from '../src/game/life';
import { createFinance,stepMarket,aggregateCandles,liquidationPrice } from '../src/game/lifeFinance';
import { advanceBody } from '../src/game/lifeHealth';
import { establishRelationship } from '../src/game/romance';
import { advanceGraduateMonth,graduateLock } from '../src/game/graduate';
import { LIFE_TASKS } from '../src/game/lifeTasks';
import { UNIVERSITIES } from '../src/game/data';
const valid=(g:ReturnType<typeof createGame>)=>assert.ok(validateGame(JSON.parse(JSON.stringify(g))),'state survives save');
function playing(){const g=createGame();Object.assign(g,{started:true,week:40,phase:'ending',examAnswers:[0,0,0],examScore:600,admittedId:UNIVERSITIES[0].id,admittedMajor:UNIVERSITIES[0].majors[0],seed:58310});return chooseLife(startLife(g).game,0).game;}
function next(g:ReturnType<typeof createGame>){if(g.life.pending)g=chooseLife(g,0).game;return advanceLife(g).game;}
test('schema1 saves preserve wealth and body while migrating news, cost basis and actual study clock',()=>{const old=playing() as any;old.life.schema=1;old.life.weeks=80;old.life.finance.holdings.ETH=.5;delete old.life.originWeek;for(const key of ['candles','news','basis','trades','sentiment'])delete old.life.finance[key];for(const key of ['partTime','wageFactor','delayed','arrearsWeeks','arrears','claimDue','pensionWeeks','paidWeeks'])delete old.life.work[key];for(const key of ['costIndex','rentIndex','shortfall','aidDue','aidCooldown','deductibleYear','deductibleSpent','excluded'])delete old.life.economy[key];for(const key of ['marriedWeek','partnerJob','partnerWorking','careShare','coParent','prenatal'])delete old.life.family[key];const migrated=validateGame(old)!;assert.ok(migrated);assert.equal(migrated.life.schema,2);assert.equal(migrated.stats.money,old.stats.money);assert.equal(migrated.life.finance.basis.ETH,9000);assert.ok(migrated.life.finance.candles.ETH.length);assert.equal(migrated.life.finance.candles.ETH.at(-1)!.close,migrated.life.finance.prices.ETH);assert.equal(migrated.life.finance.candles.ETH.at(-1)!.day,80*7-1);valid(migrated);});
test('same news, week and seed produce identical OHLC; positive and negative news produce different prices',()=>{const f=createFinance();const make=(impact:number)=>({...structuredClone(f),news:[{id:'shock',week:0,category:'市场' as const,title:'虚构报道',text:'预期变化',impacts:{ETH:impact},duration:3,rent:0,wages:0}]});const positive=stepMarket(make(.07),17,1),negative=stepMarket(make(-.07),17,1);assert.ok(positive.finance.prices.ETH>negative.finance.prices.ETH);assert.deepEqual(stepMarket(make(.07),17,1),positive);for(const c of positive.finance.candles.ETH){assert.ok(c.high>=Math.max(c.open,c.close));assert.ok(c.low<=Math.min(c.open,c.close));assert.ok(c.volume>0);}assert.ok(positive.finance.candles.ETH.at(-7)!.news.includes('shock'));});
test('weekly candles preserve true daily high, low, volume and news markers',()=>{const f=stepMarket(createFinance(),99,1).finance,c=f.candles.ETH.slice(-7),w=aggregateCandles(c,7)[0];assert.equal(w.open,c[0].open);assert.equal(w.close,c[6].close);assert.equal(w.high,Math.max(...c.map(x=>x.high)));assert.equal(w.low,Math.min(...c.map(x=>x.low)));assert.equal(w.volume,c.reduce((n,x)=>n+x.volume,0));});
test('news remains stable on reload and fresh headlines avoid the recent six releases',()=>{let f=createFinance();for(let week=1;week<=26;week++){f=stepMarket(f,1234+week,week).finance;const ids=f.news.slice(0,7).map(n=>n.id.split(':')[0]);assert.equal(new Set(ids).size,ids.length);}let g=playing();for(let i=0;i<10;i++)g=next(g);const saved=validateGame(g)!;assert.deepEqual(saved.life.finance,g.life.finance);});
test('intraweek liquidation remains final even when closing price recovers',()=>{let found=false;for(let seed=1;seed<500;seed++){const f=createFinance();f.positions=[{id:1,asset:'ETH',kind:'perpetual',side:'long',entry:f.prices.ETH,quantity:1000/f.prices.ETH,margin:100,leverage:10,expiry:4,funding:0}];f.nextId=2;const r=stepMarket(f,seed,1);if(!r.finance.positions.length&&r.finance.prices.ETH>f.prices.ETH){found=true;assert.ok(r.messages.some(x=>x.includes('周内')));assert.equal(r.finance.realized,-100);break;}}assert.ok(found,'a recovered close still has a liquidating low');});
test('margin can move independently of cash and unsafe withdrawals are blocked',()=>{let g=playing();g.stats.money=10000;g=trade(g,'perpetual','ETH',500,5).game;const line=liquidationPrice(g.life.finance.positions[0]),cash=g.stats.money;g=adjustMargin(g,g.life.finance.positions[0].id,200).game;assert.equal(g.stats.money,cash-200);assert.ok(liquidationPrice(g.life.finance.positions[0])<line);assert.ok(adjustMargin(g,1,-690).error);g=adjustMargin(g,1,-100).game;valid(g);});
test('spot average cost includes fees and profit is realized only for sold quantity',()=>{let g=playing();g.stats.money=10000;g=trade(g,'buy','ETH',1000).game;g.life.finance.prices.ETH*=2;g=trade(g,'sell','ETH',1000).game;assert.ok(Math.abs(g.life.finance.basis.ETH-500.5)<.01);assert.ok(Math.abs(g.life.finance.realized-498.5)<.01);assert.equal(g.life.finance.trades.length,2);valid(g);});
test('student work plans attend class and complete actual twenty-hour paid shifts',()=>{let g=playing();g.life.work.job='shop';g.life.work.partTime=true;const r=advanceLifePlan(g,4);g=r.game;assert.equal(g.life.education.credits,4);assert.equal(g.life.work.hours,80);assert.equal(g.life.work.paidWeeks,4);assert.equal(g.life.work.missed,0);valid(g);});
test('unworked weeks cannot create wages; arrears require shifts and arrive after a real waiting period',()=>{let g=playing();g.life.stage='society';g.life.education.enrolled=false;g.life.work.job='shop';g.life.pending='salary-delay';g=chooseLife(g,0).game;assert.equal(g.life.work.arrears,0);g=lifeAction(g,'work').game;g=advanceLife(g).game;assert.equal(g.life.work.arrears,720);assert.equal(g.life.work.paidWeeks,0);assert.ok(!g.life.economy.ledger.some(t=>t.label.includes('周工资')));g=advanceLife(g).game;assert.equal(g.life.work.arrears,720);g=advanceLife(g).game;assert.equal(g.life.work.arrears,0);assert.equal(g.life.work.paidWeeks,1);assert.equal(g.life.economy.ledger.filter(t=>t.label==='欠薪追索到账').length,1);valid(g);});
test('poverty affects diet and pressure; aid reduces debt after four weeks without minting cash',()=>{let g=playing();g.life.education.enrolled=false;g.stats.money=0;const diet=g.life.body.habits.diet;g=advanceLife(g).game;assert.ok(g.life.economy.debt>0);assert.ok(g.life.body.habits.diet<diet);assert.ok(g.stats.stress>20);g=economicOperation(g,'aid').game;assert.equal(g.stats.money,0);for(let i=0;i<3;i++)g=next(g);assert.ok(g.life.economy.aidDue>=0);g=next(g);assert.equal(g.life.economy.aidDue,-1);assert.equal(g.stats.money,0);assert.ok(economicOperation(g,'aid').error);valid(g);});
test('insurance deductible is annual and excluded diagnoses do not consume it',()=>{let g=playing();g.stats.money=10000;g=medicalOperation(g,'insurance:basic').game;g=medicalOperation(g,'blood').game;g=medicalOperation(g,'glucose').game;assert.equal(g.life.economy.deductibleSpent,500);assert.equal(g.life.economy.ledger[0].amount,-283);valid(g);g.life.body.conditions.push({id:'diabetes',stage:'diagnosed',severity:40,since:0,treated:-1,discovered:true});g=medicalOperation(g,'insurance:commercial').game;assert.deepEqual(g.life.economy.excluded,['diabetes']);valid(g);});
test('diabetes uses two distinct-week abnormal checks and stores numerical results',()=>{let g=playing();g.life.body.conditions.push({id:'diabetes',stage:'latent',severity:20,since:0,treated:-1,discovered:false});g=medicalOperation(g,'glucose').game;assert.equal(g.life.body.conditions[0].discovered,false);assert.ok(g.life.body.tests[0].readings!.glucose>=7);g=advanceLife(g).game;g=medicalOperation(g,'glucose').game;assert.equal(g.life.body.conditions[0].discovered,true);valid(g);});
test('diagnostic indications expire and cancer imaging clues precede biopsy confirmation',()=>{let g=playing();g.life.body.conditions.push({id:'kidneyCancer',stage:'symptoms',severity:40,since:0,treated:-1,discovered:false});g=medicalOperation(g,'scan').game;assert.equal(g.life.body.conditions[0].discovered,false);g.life.weeks=14;assert.ok(medicalOperation(g,'biopsy').error);g=medicalOperation(g,'scan').game;g=medicalOperation(g,'biopsy').game;assert.equal(g.life.body.conditions[0].discovered,true);valid(g);});
test('pausing chronic care raises severity rather than granting permanent stability',()=>{let g=playing();g.life.body.conditions.push({id:'diabetes',stage:'diagnosed',severity:50,since:0,treated:-1,discovered:true});g=medicalOperation(g,'treat:diabetes').game;const before=g.life.body.conditions[0].severity;g=medicalOperation(g,'pause:diabetes').game;g=advanceLife(g).game;assert.ok(g.life.body.conditions[0].severity>before);assert.notEqual(g.life.body.conditions[0].stage,'stable');valid(g);});
test('long family tasks count time since marriage; partner income stops with work',()=>{let g=establishRelationship(playing(),'su');g.life.baseAge=24;g.life.weeks=200;g.life.family.affection=90;g=chooseLife(familyOperation(g,'propose').game,0).game;g=familyOperation(g,'marry').game;assert.equal(LIFE_TASKS.find(t=>t.id==='home')!.progress(g),0);g=familyOperation(g,'partner-work').game;g=advanceLife(g).game;assert.ok(!g.life.economy.ledger.some(t=>t.label.includes('伴侣排班')));valid(g);});
test('separation preserves pregnancy, shared responsibility and saves',()=>{let g=establishRelationship(playing(),'su');g.life.baseAge=24;g.life.family.affection=90;g=chooseLife(familyOperation(g,'propose').game,0).game;g=familyOperation(g,'marry').game;g=chooseLife(familyOperation(g,'baby').game,0).game;g=chooseLife(familyOperation(g,'breakup').game,0).game;assert.ok(g.life.family.pregnancy);assert.equal(g.life.family.coParent,true);valid(g);});
test('inheritance preserves actual teenage age, body and unfinished adult degree; spouse retains a share',()=>{let g=establishRelationship(playing(),'su');g.life.weeks=1500;g.life.family.spouse='su';g.life.family.children=[{id:'teen',name:'予川',gender:'male',bornWeek:616,education:50,care:70},{id:'adult',name:'予禾',gender:'female',bornWeek:200,education:60,care:70}];g.stats.money=10000;g.life.economy.debt=2000;die(g,'意外');const teen=inheritLife(g,'teen',createGame()).game;assert.equal(lifeAge(teen),17);assert.equal(teen.life.stage,'school');assert.equal(teen.stats.money,2000);assert.ok(graduateLock(teen));valid(teen);const adult=inheritLife(g,'adult',createGame()).game;assert.equal(lifeAge(adult),25);assert.equal(adult.life.education.degree,false);valid(adult);});
test('graduate relationship cannot independently advance time or generate free cash during lifetime',()=>{const g=playing();g.graduate.unlocked=true;const r=advanceGraduateMonth(g);assert.ok(r.error);assert.equal(r.game,g);});
test('malformed candle, news impact and structured labs are rejected',()=>{for(const mutate of [(g:any)=>g.life.finance.candles.ETH[0].high=0,(g:any)=>g.life.finance.news[0].impacts.ETH=Infinity,(g:any)=>g.life.finance.basis.ETH=-1,(g:any)=>g.life.work.arrears=-1]){const g=playing();mutate(g);assert.equal(validateGame(g),null);}});

test('aid paperwork takes four weeks and offsets debt before cash',()=>{let g=playing();g.life.pending='tuition';g.life.economy.debt=300;g=chooseLife(g,0).game;const money=g.stats.money;assert.equal(g.stats.money,money);assert.equal(g.life.claims[0].due,4);for(let i=0;i<3;i++)g=next(g);assert.equal(g.life.claims.length,1);g=next(g);assert.equal(g.life.claims.length,0);assert.ok(g.life.memories.some(m=>m.title==='办理回执'));valid(g);});
test('regular oncology review does not reset the completed course or remission horizon',()=>{let g=playing();g.life.body.conditions.push({id:'aml',stage:'diagnosed',severity:35,since:0,treated:-1,discovered:true});g=medicalOperation(g,'treat:aml').game;const remission=g.life.body.conditions[0].remission;g.life.weeks=13;g.life.actions=0;g.life.used=[];g=medicalOperation(g,'treat:aml').game;assert.equal(g.life.body.conditions[0].remission,remission);assert.equal(g.life.body.conditions[0].treated,0);valid(g);});
test('a child earns a degree through two hundred eight actual college weeks, not its birthday',()=>{let g=establishRelationship(playing(),'su');g.life.weeks=1200;g.life.stage='society';g.life.education.enrolled=false;g.life.education.degree=true;g.life.education.credits=160;g.life.education.entered=992;g.life.family.spouse='su';g.life.family.partnerJob='shop';g.life.family.careShare=.85;g.life.work.job='shop';g.stats.money=100000;g.life.family.children=[{id:'grown',name:'予禾',gender:'female',bornWeek:265,education:80,care:100}];for(let i=0;i<208;i++){if(g.life.pending)g=chooseLife(g,0).game;g=lifeAction(g,'work').game;g=lifeAction(g,'care').game;g=lifeAction(g,'rest').game;g=advanceLife(g).game;assert.ok(!g.life.death&&!g.life.body.emergency);if(i===100){assert.equal(g.life.family.children[0].profile!.degree,false);valid(g);}}const p=g.life.family.children[0].profile!;assert.equal(p.collegeWeeks,208);assert.equal(p.credits,160);assert.equal(p.degree,true);die(g,'寿终');const child=inheritLife(g,'grown',createGame()).game;assert.equal(child.life.education.degree,true);valid(child);});

test('fractional-cent trading and margin inputs cannot create free assets',()=>{let g=playing();const money=g.stats.money;assert.ok(trade(g,'buy','ETH',.001).error);g=trade(g,'buy','ETH',.01).game;assert.equal(g.stats.money,money-.02);g=trade(g,'perpetual','ETH',10,2).game;assert.ok(adjustMargin(g,1,.001).error);valid(g);});
