import { useState, type Dispatch, type SetStateAction } from 'react';
import { Heart, MessageCircle, ArrowRight } from 'lucide-react';
import { CHARACTERS, ITEMS, imagePath } from '../game/data';
import { GRADUATE_CHAPTERS, advanceGraduateMonth, beginGraduateScene, contactGraduate, giftGraduate, graduateDate, graduateLock, graduateSceneLock, graduateStory, resolveGraduateScene, setGraduateBoundary, setGraduateFollowing, unlockGraduate } from '../game/graduate';
import { changeRelationship } from '../game/romance';
import type { GameState, GraduateOperation } from '../game/types';

export default function GraduateRomancePanel({ game, setGame, notify, onChat }: { game: GameState; setGame: Dispatch<SetStateAction<GameState>>; notify: (message: string) => void; onChat: () => void }) {
  const [gift, setGift] = useState('milk'), [splitConfirm, setSplitConfirm] = useState(false);
  const run = (operation: (current: GameState) => { game: GameState; error?: string }) => { const result = operation(game); if (result.error) notify(result.error); else setGame(result.game); };
  const state = game.graduate, lock = graduateLock(game), story = graduateStory(game);
  const sceneButton = (operation: GraduateOperation, title: string, cost = '1 次相处') => { const reason = graduateSceneLock(game, operation); return <button key={operation} aria-label={title} aria-describedby={`graduate-hint-${operation}`} className="secondary-button" disabled={!!reason} title={reason ?? title} onClick={() => run(current => beginGraduateScene(current, operation))}><span><strong>{title}</strong><small id={`graduate-hint-${operation}`}>{reason ?? cost}</small></span><ArrowRight size={16}/></button>; };
  return <div className="graduate-panel"><section className="graduate-intro"><img src={imagePath(CHARACTERS.teacher.image)} alt="老陈"/><div><span className="little-label">毕业以后的另一页 · {game.life.active?'与人生时间同步':'相处手记'}</span><h3>课桌之外，重新认识</h3><p>{game.life.active?graduateDate(game)+'，':'2027年9月，毕业已超过一年。'}你已成年，老陈不再对你授课、评分或管理。从普通朋友重新认识，交往需要双方明确答应。</p></div></section>
    {lock ? <div className="empty-state"><Heart size={32}/><h3>先走完属于你的高三</h3><p>{lock}。在校期间保留师生交流，恋爱入口不会提前解锁。</p></div> : !state.unlocked ? <button className="primary-button" onClick={() => run(unlockGraduate)}>开启毕业后的重逢<ArrowRight size={16}/></button> : story ? <section className="graduate-story"><span className="little-label">{graduateDate(game)} · 当前这一页</span><h3>{story.title}</h3><p>{story.text}</p><div className="story-choices">{story.choices.map((choice, index) => <button className="story-choice" key={choice} onClick={() => run(current => resolveGraduateScene(current, index))}><span className="choice-letter">{index === 0 ? 'A' : 'B'}</span><span>{choice}</span><ArrowRight size={16}/></button>)}</div><p className="fine-print">选择后自动存档；刷新会继续这一页。</p></section> : <>
      <div className="graduate-overview"><span>{graduateDate(game)} · {state.partner ? '彼此答应的交往' : state.status === 'broken' ? '分开后的生活' : '重新认识的朋友'}</span><div className="love-bond-values"><span>信任 <b>{state.trust}</b></span><span>心动 <b>{state.affection}</b></span><span>了解 <b>{state.understanding}</b></span></div><p>不同月见面 {state.meetMonths.length} 次 · 本月相处 {state.actions} / 2 · 生活费 ¥ {game.stats.money}</p><button className="text-button" onClick={onChat}><MessageCircle size={15}/>查看老陈的 IM</button></div>
      {game.social.partner && <div className="graduate-existing"><p>你仍与{CHARACTERS[game.social.partner].name}交往，新的表白暂时关闭。原有回忆会保留。</p><button className="secondary-button" onClick={() => { if (!splitConfirm) setSplitConfirm(true); else { run(current => changeRelationship(current, current.social.partner!, 'breakup')); setSplitConfirm(false); } }}>{splitConfirm ? '确认结束现有交往' : '认真处理现有关系'}</button>{splitConfirm && <button className="text-button" onClick={() => setSplitConfirm(false)}>继续原来的交往</button>}</div>}
      <section className="graduate-actions"><h4>{state.partner ? '一起生活，也各自成长' : '从普通的相处开始'}</h4><div className="graduate-action-grid">{sceneButton('reunion', '完成毕业后的重逢')}{sceneButton('meet', '约一次见面')}{sceneButton('talk', '认真聊聊近况')}{sceneButton('confess', state.status === 'broken' ? '讨论重新开始' : '主动表达喜欢')}{sceneButton('date', '共同安排约会')}{sceneButton('hand', '牵手', '本月一次亲近，不扣相处行动')}{sceneButton('hug', '拥抱', '本月一次亲近，不扣相处行动')}{sceneButton('kiss', '轻吻', '本月一次亲近，不扣相处行动')}{sceneButton('birthday', state.partner ? '一起过情侣生日' : '朋友的生日祝福')}</div><div className="graduate-gifts"><button className="secondary-button" disabled={!state.meetMonths.length || state.contactMonths.includes(state.month)} onClick={() => run(contactGraduate)}>主动发消息 · 每月一次</button><select aria-label="毕业后礼物" value={gift} onChange={event => setGift(event.target.value)}>{ITEMS.map(item => <option key={item.id} value={item.id}>{item.name} · 已有 {game.inventory[item.id]} / 购买 ¥{item.price}</option>)}</select><button className="secondary-button" disabled={!state.meetMonths.length || state.giftMonths.includes(state.month)} onClick={() => run(current => giftGraduate(current, gift))}>送礼 · 每月一次</button></div><p className="fine-print">消息和送礼免费使用相处次数；已有礼物从背包扣除，否则按标价购买。10 月首份礼物加成 50%。</p></section>
      <section className="graduate-chapters"><h4>六章相伴手记 · 至少跨六个月</h4>{GRADUATE_CHAPTERS.map(([title], index) => sceneButton(`chapter-${index}` as GraduateOperation, `${index + 1}. ${title}`))}</section>
      {state.partner && <section className="graduate-boundaries"><h4>我们的约定</h4><label><input type="checkbox" checked={state.following} onChange={event => run(current => setGraduateFollowing(current, event.target.checked))}/>邀请同行，地图头像与横幅同步</label><label><input type="checkbox" checked={state.touchAllowed} onChange={event => run(current => setGraduateBoundary(current, event.target.checked))}/>愿意讨论牵手、拥抱与轻吻；每次仍可拒绝</label>{sceneButton('breakup', '认真谈谈分手', '明确选择后才结束，回忆保留')}</section>}
      <div className="graduate-months"><p>{game.life.active?'结束本周推进统一时间，进入新月份时恢复2次相处机会；工作与生活费在账本结算。':'下一月恢复2次相处行动，补充¥60生活费；校园周数与高考结果保留。'}</p><button className="primary-button" disabled={game.life.active||state.month >= 23} onClick={() => run(advanceGraduateMonth)}>{game.life.active?'请在地图结束本周':state.month >= 23 ? '两年手记已收好' : '继续下一个月'}<ArrowRight size={16}/></button></div>
      <section className="graduate-memories"><h4>已经一起走过</h4>{state.memories.length ? [...state.memories].reverse().map(memory => <article key={memory.id}><small>重逢第 {memory.month + 1} 月</small><h4>{memory.title}</h4><p>{memory.result}</p></article>) : <p>完成重逢后，第一段回忆会留在这里。</p>}</section>
    </>}
  </div>;
}
