import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ShieldCheck } from 'lucide-react';
import { CHARACTERS, ROMANCE_IDS, imagePath } from '../game/data';
import { actionLock, advanceLifePlan, applyJob, closePosition, economicOperation, familyOperation, jobLock, lifeAction, lifeAge, lifePartner, marriageLock, medicalOperation, removeLiquidity, trade, type LifeResult } from '../game/life';
import { ASSETS, DISEASES, JOBS, LIFE_ACTIONS, MEDICAL_TESTS, MINI_GAMES } from '../game/lifeData';
import { medicalLock } from '../game/lifeHealth';
import { portfolioValue, positionEquity, swapQuote } from '../game/lifeFinance';
import { abandonMiniGame, answerMiniGame, BUDGET_QUESTIONS, INTERVIEW_QUESTIONS, LOGIC_QUESTIONS, matchedCards, memoryBoard, startMiniGame } from '../game/lifeGames';
import { claimLifeTask, LIFE_TASKS } from '../game/lifeTasks';
import type { LifePanel } from '../game/lifeTypes';
import type { GameState, RomanceId } from '../game/types';
export type LifeProps = { game: GameState; run: (op: (g: GameState) => LifeResult) => void; show: (p: LifePanel) => void };
export const money = (n: number) => n.toLocaleString('zh-CN', { maximumFractionDigits: 2 });
export function LifeOverview({ game: g, run, show }: LifeProps) {
  const l = g.life, e = l.economy, j = JOBS.find(j => j.id === l.work.job);
  return <div className="life-panel-stack"><div className="life-stat-grid"><div><small>年龄</small><strong>{lifeAge(g).toFixed(1)} 岁</strong><span>第 {l.generation} 代 · 第 {l.weeks + 1} 周</span></div><div><small>可用现金</small><strong>¥{money(g.stats.money)}</strong><span>资产 ¥{money(portfolioValue(l.finance))}</span></div><div><small>待偿还欠款</small><strong>¥{money(e.debt)}</strong><span>每周自动分期，账本可核对</span></div><div><small>工作与学习</small><strong>{j?.name ?? (l.work.retired ? '已退休' : '尚未就业')}</strong><span>{l.education.degree ? '已取得本科' : l.education.enrolled ? `${l.education.credits}/160 学分 · ${Math.min(208, l.weeks)}/208 周` : '自主职业路径'}</span></div></div>
    <article className="life-paper"><h3>生活的固定支出</h3><p>饮食 ¥95 / 周；宿舍 ¥35、合租 ¥160、整租 ¥360 / 周。在读学费 ¥110 / 周。孩子、治疗与保险另计。费用都是游戏参数。</p><label className="life-field">居住安排<select value={e.rent} onChange={ev => run(g => economicOperation(g, 'rent', ev.target.value))}><option value="dorm" disabled={!l.education.enrolled || l.education.degree}>学生宿舍</option><option value="shared">合租</option><option value="apartment">整租小家</option></select></label><div className="life-button-row"><button className="secondary-button" disabled={!e.debt || !g.stats.money} onClick={() => run(g => economicOperation(g, 'repay'))}>用可用现金偿还欠款</button><button className="text-button" onClick={() => show('health')}>医保与医疗账单 <ArrowRight size={14}/></button></div></article>
    <article className="life-paper"><h3>按日程继续生活</h3><p>自动安排课程或工作、运动或照护、休息。遇到新事件、身体提醒、急症或死亡会立即停下，等待你的选择。</p><div className="life-button-row">{[4, 13, 52].map(weeks => <button className="secondary-button" key={weeks} onClick={() => run(g => advanceLifePlan(g, weeks))}>按计划生活 {weeks} 周</button>)}</div></article><article className="life-paper"><h3>收支账本</h3><p>累计流入 ¥{money(e.income)} · 累计流出 ¥{money(e.expenses)}。包含资产买卖本金，不能把流入当成利润。</p><div className="life-ledger">{e.ledger.slice(0, 45).map((t, i) => <div key={`${t.week}-${i}`}><span><small>第 {t.week + 1} 周</small>{t.label}</span><b className={t.amount >= 0 ? 'gain' : 'loss'}>{t.amount >= 0 ? '+' : ''}{money(t.amount)}</b></div>)}{!e.ledger.length && <p>新的账单会在行动和周末结算后出现。</p>}</div></article></div>;
}
export function LifeWork({ game: g, run, show }: LifeProps) {
  const l = g.life, job = JOBS.find(j => j.id === l.work.job);
  return <div className="life-panel-stack"><article className="life-paper"><h3>{l.education.school} · {l.education.major}</h3><p>{l.education.degree ? '本科学历' : l.education.enrolled ? '本科在读' : '未取得本科'} · 专业技能 {l.skills.technical.toFixed(1)} · 沟通 {l.skills.communication.toFixed(1)} · 实践 {l.skills.practical.toFixed(1)}</p><p>累计排班 {l.work.experience} 周 / {l.work.hours} 小时。{job ? `当前：${job.name}。本周${l.used.includes('work') ? '已完成排班，周末发薪' : '尚未上班'}。` : '技能不能跳过招聘的学历筛选，学校标签也不能代表全部能力。'}</p><div className="life-button-row"><button className="primary-button" disabled={l.used.includes('game:interview') || l.actions >= 3} onClick={() => { run(g => startMiniGame(g, 'interview')); show('game'); }}>本周互动面试 · 1 行动</button><button className="text-button" onClick={() => show('place')}>前往地点安排上班 / 学习</button>{job && <button className="secondary-button" onClick={() => run(g => economicOperation(g, 'quit'))}>离职</button>}{lifeAge(g) >= 60 && !l.work.retired && <button className="secondary-button" onClick={() => run(g => economicOperation(g, 'retire'))}>选择退休</button>}</div></article>
    <div className="life-card-grid">{JOBS.map(j => { const lock = jobLock(g, j.id); return <article className="life-paper" key={j.id}><span className="little-label">{j.degree ? '本科岗位' : '开放学历'} · {j.hours} 小时 / 周</span><h3>{j.name}</h3><strong>周薪 ¥{j.wage}</strong><p>专业技能 {j.skill} · 面试 {j.interview}{j.prestige ? ` · 学校筛选 ${j.prestige}` : ''}</p><p>排班消耗体力 {j.cost}、压力 +{j.stress}。工资在完成排班后的周末结算。</p><button className="secondary-button" disabled={!!lock} onClick={() => run(g => applyJob(g, j.id))}>投递并签约 · 1 行动</button><small className="life-lock">{lock ?? '岗位条件符合，可投递。'}</small></article>; })}</div></div>;
}
export function LifeHealth({ game: g, run }: LifeProps) {
  const l = g.life, b = l.body;
  const names = { metabolic: '代谢储备', vascular: '循环储备', cardiac: '心脏储备', renal: '肾脏储备', respiratory: '呼吸储备', marrow: '造血储备', skeletal: '骨骼储备' };
  return <div className="life-panel-stack"><p className="life-disclaimer">健康指标、病程、风险概率和收费是虚构玩法，不用于诊断或估计现实风险。持续不适应在现实中就医。</p>{b.emergency && <article className="life-emergency" role="alert"><h3>立即救治 · {DISEASES[b.emergency].name}</h3><p>{DISEASES[b.emergency].symptom}。急救不会因为行动用完或现金不足被阻挡。</p><button className="primary-button" onClick={() => run(g => medicalOperation(g, 'rescue'))}>立即急救，费用记入账本</button></article>}
    <article className="life-paper"><h3>高中留下的习惯</h3><p>累计记录高中 {b.schoolWeeks} 周。好习惯可以降低部分风险，却不能保证不会生病。癌症和白血病保留独立背景风险。</p><div className="life-stat-grid">{Object.entries({ 饮食: b.habits.diet, 睡眠: b.habits.sleep, 活动: b.habits.movement, 累积负荷: b.habits.strain }).map(([name, value]) => <div key={name}><small>{name}</small><strong>{value.toFixed(0)}/100</strong></div>)}</div></article>
    <div className="life-body-grid">{Object.entries(b.internal).map(([key, value]) => <label key={key}>{names[key as keyof typeof names]}<b>{value.toFixed(1)}</b><progress max="100" value={value}/></label>)}</div>
    {!!b.notices.length && <article className="life-paper"><h3>本周身体提醒</h3>{b.notices.map(text => <p key={text}>{text}</p>)}</article>}
    <article className="life-paper"><h3>保障与条款</h3><p>基础方案 ¥18 / 周，起付 500 后模拟报销 55%。商业方案 ¥75 / 周、13 周等待期，模拟报销 70%，已确诊病况可能被除外。费用都由游戏设定。</p><div className="life-button-row">{(['none', 'basic', 'commercial'] as const).map(p => <button className="secondary-button" aria-pressed={l.economy.insurance === p} key={p} disabled={!!b.emergency || l.economy.insurance === p} onClick={() => run(g => medicalOperation(g, `insurance:${p}`))}><ShieldCheck size={14}/>{p === 'none' ? '暂无保险' : p === 'basic' ? '基础方案' : '商业方案'}</button>)}</div></article>
    <div className="life-card-grid">{MEDICAL_TESTS.map(t => { const lock = medicalLock(g, t.id); return <article className="life-paper" key={t.id}><h3>{t.name}</h3><p>{t.hint}</p><button className="secondary-button" disabled={!!b.emergency || !!lock || l.actions >= 3} onClick={() => run(g => medicalOperation(g, t.id))}>检查 ¥{t.price} · 1 行动</button><small className="life-lock">{lock ?? '费用可报销或形成欠款；先检查再进一步确认。'}</small></article>; })}</div>
    <article className="life-paper"><h3>确诊与后续治疗</h3>{b.conditions.filter(c => c.discovered).map(c => <div className="life-condition" key={c.id}><strong>{DISEASES[c.id].name}</strong><p>{c.stage === 'stable' ? '稳定治疗 / 周末自动随访' : c.stage === 'progressing' ? '病程进展，需要治疗' : '已诊断 / 等待治疗'}</p><button className="secondary-button" disabled={!!b.emergency || c.stage === 'stable' || l.actions >= 3} onClick={() => run(g => medicalOperation(g, `treat:${c.id}`))}>专科治疗 / 必要时手术 · 1 行动 · 总额 ¥{DISEASES[c.id].treatment}</button></div>)}{!b.conditions.some(c => c.discovered) && <p>当前没有确诊记录。没有确诊不代表所有病况都已排除。</p>}</article>
    <article className="life-paper"><h3>化验与检查记录</h3>{b.tests.slice(0, 20).map((t, i) => <div className="life-condition" key={i}><small>第 {t.week + 1} 周 · {MEDICAL_TESTS.find(x => x.id === t.test)?.name}</small><p>{t.text}</p></div>)}</article></div>;
}
export function LifeFinance({ game: g, run }: LifeProps) {
  const [tab, setTab] = useState('spot'), [asset, setAsset] = useState('ETH'), [amount, setAmount] = useState('100'), [leverage, setLeverage] = useState(2), [side, setSide] = useState<'long' | 'short'>('long'); const f = g.life.finance, value = Number(amount), price = f.prices[asset];
  const invalid = !Number.isFinite(value) || value <= 0;
  return <div className="life-panel-stack"><p className="life-disclaimer">全部行情、资金和交易为本地游戏模拟，不连接真实钱包。杠杆可能损失全部逐仓保证金，LP 会有滑点和无常损失。</p><div className="paper-tabs life-tabs">{[['spot', '现货 / 股票'], ['contract', '永续 / 交割'], ['amm', 'Uniswap v2']].map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} aria-pressed={tab === id} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div className="life-stat-grid"><div><small>可用现金</small><strong>¥{money(g.stats.money)}</strong></div><div><small>持仓与保证金权益</small><strong>¥{money(portfolioValue(f))}</strong></div><div><small>累计手续费</small><strong>¥{money(f.fees)}</strong></div><div><small>合约已实现盈亏</small><strong>¥{money(f.realized)}</strong></div></div>
    <div className="life-card-grid">{ASSETS.map(a => { const series = f.series[a.id], min = Math.min(...series) * .98, max = Math.max(...series) * 1.02; return <button key={a.id} className={`life-paper life-ticker ${asset === a.id ? 'selected' : ''}`} onClick={() => setAsset(a.id)}><strong>{a.name}</strong><span>¥{money(f.prices[a.id])}</span><svg viewBox="0 0 260 70" role="img" aria-label={`${a.name}最近 ${series.length} 周模拟价格`}><polyline fill="none" stroke="currentColor" strokeWidth="2" points={series.map((v, i) => `${i / Math.max(1, series.length - 1) * 260},${65 - (v - min) / (max - min) * 60}`).join(' ')}/></svg><small>持仓 {f.holdings[a.id].toFixed(6)} · ¥{money(f.holdings[a.id] * f.prices[a.id])}</small></button>; })}</div>
    <article className="life-paper"><h3>{tab === 'amm' ? '常数乘积池 x × y = k' : tab === 'contract' ? '逐仓合约' : '按金额交易'}</h3><div className="life-form-row"><label className="life-field">资产<select value={tab === 'amm' ? 'ETH' : asset} disabled={tab === 'amm'} onChange={e => setAsset(e.target.value)}>{ASSETS.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="life-field">{tab === 'contract' ? '保证金（元）' : '交易金额（元）'}<input aria-label="交易金额" type="number" min="1" max="999999" step="1" value={amount} onChange={e => setAmount(e.target.value)}/></label>{tab === 'contract' && <><label className="life-field">杠杆<select value={leverage} onChange={e => setLeverage(Number(e.target.value))}>{[1, 2, 3, 5, 10].map(n => <option key={n} value={n}>{n}×</option>)}</select></label><label className="life-field">方向<select value={side} onChange={e => setSide(e.target.value as typeof side)}><option value="long">做多</option><option value="short">做空</option></select></label></>}</div>
      {tab === 'spot' && <><p>买入手续费 0.1%，卖出按当前市值计费，不能卖出未持有的资产。</p><div className="life-button-row"><button className="primary-button" disabled={invalid} onClick={() => run(g => trade(g, 'buy', asset, value))}>买入现货</button><button className="secondary-button" disabled={invalid} onClick={() => run(g => trade(g, 'sell', asset, value))}>卖出等值持仓</button></div></>}
      {tab === 'contract' && <><p>仅 BTC / ETH。名义金额 ¥{money(value * leverage)}，开仓费 ¥{money(value * leverage * .001)}。维持保证金为名义金额的 0.5%；每周结算行情与资金费，交割在 4 周后现金结算。</p><div className="life-button-row"><button className="primary-button" disabled={invalid || !['BTC', 'ETH'].includes(asset)} onClick={() => run(g => trade(g, 'perpetual', asset, value, leverage, side))}>开永续仓位</button><button className="secondary-button" disabled={invalid || !['BTC', 'ETH'].includes(asset)} onClick={() => run(g => trade(g, 'delivery', asset, value, leverage, side))}>开 4 周交割合约</button></div></>}
      {tab === 'amm' && <><p>池储备 {f.pool.eth.toFixed(4)} ETH / ¥{money(f.pool.cash)}。兑换费 0.3%，大额交易会偏离盘口价格。</p><p>预计买入 {invalid ? '0' : swapQuote(f, 'buy', value).toFixed(6)} ETH；对应市场价数量 {(invalid ? 0 : value / f.prices.ETH).toFixed(6)} ETH。LP 投入还需要 {(invalid ? 0 : value * f.pool.eth / f.pool.cash).toFixed(6)} ETH。</p><div className="life-button-row"><button className="primary-button" disabled={invalid} onClick={() => run(g => trade(g, 'swap-buy', 'ETH', value))}>现金兑换 ETH</button><button className="secondary-button" disabled={invalid} onClick={() => run(g => trade(g, 'swap-sell', 'ETH', value))}>等值 ETH 换现金</button><button className="secondary-button" disabled={invalid} onClick={() => run(g => trade(g, 'lp-add', 'ETH', value))}>按比例提供流动性</button><button className="text-button" disabled={!f.pool.shares} onClick={() => run(removeLiquidity)}>撤回全部 LP</button></div><p>LP 份额 {f.pool.shares.toFixed(3)} / {f.pool.supply.toFixed(3)} · 累计投入 ¥{money(f.pool.deposited)}；当前权益 ¥{money(f.pool.shares / f.pool.supply * (f.pool.eth * f.prices.ETH + f.pool.cash))}。</p></>}
    </article>{!!f.positions.length && <article className="life-paper"><h3>逐仓仓位</h3>{f.positions.map(p => <div className="life-condition" key={p.id}><strong>{p.asset} · {p.kind === 'perpetual' ? '永续' : `第 ${p.expiry + 1} 周交割`} · {p.side === 'long' ? '多' : '空'} {p.leverage}×</strong><p>开仓 ¥{money(p.entry)} · 当前权益 ¥{money(positionEquity(p, f.prices[p.asset]))} · 保证金 ¥{money(p.margin)} · 累计资金费 ¥{money(p.funding)}</p><button className="secondary-button" onClick={() => run(g => closePosition(g, p.id))}>平仓</button></div>)}</article>}<small>当前所选市场价格 ¥{money(price)}。价格每周推进，切换地图不会刷新行情。</small></div>;
}
export function LifeFamily({ game: g, run }: LifeProps) {
  const l = g.life, partner = lifePartner(g), [contact, setContact] = useState<RomanceId>(g.social.partner ?? 'su'), lock = marriageLock(g);
  return <div className="life-panel-stack"><article className="life-paper"><div className="life-partner"><img src={imagePath(CHARACTERS[partner ?? contact].image)} alt=""/><div><h3>{partner ? CHARACTERS[partner].name : '毕业后的心意'}</h3><p>{l.family.spouse ? '已婚 · 共同生活' : partner ? '双方确认交往' : '先相处，再认真询问对方是否愿意'} · 亲密 {l.family.affection.toFixed(0)}</p></div></div>
    {!partner && <label className="life-field">想和谁认真相处<select value={contact} onChange={e => setContact(e.target.value as RomanceId)}>{ROMANCE_IDS.map(id => <option key={id} value={id}>{CHARACTERS[id].name}</option>)}</select></label>}
    <div className="life-button-row">{(!partner || partner !== 'teacher') && <button className="secondary-button" disabled={l.actions >= 3} onClick={() => run(g => familyOperation(g, 'talk', partner ?? contact))}>认真沟通 · 1 行动</button>}{!partner && <button className="primary-button" onClick={() => run(g => familyOperation(g, 'confess', contact))}>主动表白，等待对方答复</button>}{partner && <button className="secondary-button" onClick={() => run(g => familyOperation(g, 'follow'))}>{l.family.following ? '结束同行' : '邀请一起走走'}</button>}{partner && <button className="text-button" onClick={() => run(g => familyOperation(g, 'breakup'))}>{l.family.spouse ? '讨论分开与后续照护' : '认真谈分手'}</button>}</div>
    {partner && !l.family.spouse && <><p>{lock ?? '双方达到婚龄和亲密条件，可一起讨论未来。'}</p><div className="life-button-row"><button className="primary-button" disabled={!!lock} onClick={() => run(g => familyOperation(g, 'propose'))}>认真求婚 · 双方确认</button><button className="secondary-button" disabled={!!lock || !l.family.proposed} onClick={() => run(g => familyOperation(g, 'marry'))}>登记结婚 · ¥480</button></div></>}
    {l.family.spouse && <><p>共同生活每周模拟收入 ¥210、增加支出 ¥140。工作、家务与照护需要商量。</p><div className="life-button-row"><button className="secondary-button" onClick={() => run(g => familyOperation(g, 'baby'))}>讨论孕育计划</button><button className="secondary-button" onClick={() => run(g => familyOperation(g, 'adopt'))}>共同养育计划</button></div></>}
  </article>{l.family.pregnancy && <article className="life-paper"><h3>正在共同孕育</h3><p>距离预期出生还有 {l.family.pregnancy.due - l.weeks} 周。每周照护 ¥70，出生时住院总额 ¥8500，按保障方案结算。私人过程略过。</p></article>}
    {l.family.children.map(c => <article className="life-paper" key={c.id}><h3>{c.name} · {Math.max(0, (l.weeks - c.bornWeek) / 52).toFixed(1)} 岁</h3><p>照护 {c.care.toFixed(0)} · 成长与学习 {c.education.toFixed(1)}。父母的劳动不能替代陪伴。</p></article>)}
    <article className="life-paper"><h3>关系需要持续的行动</h3><p>约会每周一次；沟通、家务和照护都能安排。孩子成长与抚养费随周次变化。</p><div className="life-button-row">{['date', 'care'].map(id => <button className="secondary-button" key={id} disabled={!!actionLock(g, id)} onClick={() => run(g => lifeAction(g, id))}>{LIFE_ACTIONS[id].name} · 1 行动</button>)}</div></article></div>;
}
export function LifeTasks({ game: g, run, show }: LifeProps) { return <div className="life-card-grid">{LIFE_TASKS.filter(t => t.visible(g)).map(t => { const p = t.progress(g), done = g.life.tasks.includes(t.id); return <article className="life-paper" key={t.id}><span className="little-label">跨周长期任务</span><h3>{t.title}</h3><p>{t.detail}</p><progress max="1" value={p}/><div className="life-button-row"><button className="secondary-button" onClick={() => show(t.target)}>去安排</button><button className="primary-button" disabled={p < 1 || done} onClick={() => run(g => claimLifeTask(g, t.id))}>{done ? '已完成' : p >= 1 ? `领取补给 ¥${t.reward}` : `${Math.floor(p * 100)}%`}</button></div></article>; })}</div>; }
export function LifeMiniGame({ game: g, run }: LifeProps) {
  const mini = g.life.game, [now, setNow] = useState(0), [revealed, setRevealed] = useState(false), beatStart = useRef(performance.now());
  const id = mini?.id, count = mini?.answers.length ?? 0;
  useEffect(() => { beatStart.current = performance.now(); if (id !== 'rhythm') return; const timer = window.setInterval(() => setNow((performance.now() - beatStart.current) % 1000), 25); return () => clearInterval(timer); }, [id, count]);
  useEffect(() => { setRevealed(true); if (id !== 'memory' || count % 2) return; const timer = setTimeout(() => setRevealed(false), 800); return () => clearTimeout(timer); }, [count, id]);
  useEffect(() => { if (id !== 'rhythm') return; const key = (e: KeyboardEvent) => { if (e.code === 'Space' && !e.repeat && (e.target as HTMLElement).tagName !== 'BUTTON') { e.preventDefault(); run(g => answerMiniGame(g, Math.round((performance.now() - beatStart.current) % 1000))); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [id, run]);
  if (!mini) return <div className="life-panel-stack"><h3>选择一个小游戏</h3><p>每种游戏每周一次，消耗 1 行动；没有现金奖池。</p><div className="life-card-grid">{MINI_GAMES.map(m => <article className="life-paper" key={m.id}><h3>{m.name}</h3><p>{m.description}</p><button className="secondary-button" disabled={g.life.actions >= 3 || g.life.used.includes(`game:${m.id}`)} onClick={() => run(g => startMiniGame(g, m.id))}>开始 · ¥{m.price} · 1 行动</button><small className="life-lock">上次成绩 {g.life.scores[m.id] ?? '—'}</small></article>)}</div></div>;
  const questions = id === 'interview' ? INTERVIEW_QUESTIONS : id === 'budget' ? BUDGET_QUESTIONS : LOGIC_QUESTIONS, question = questions[count];
  const board = memoryBoard(mini.seed), matched = matchedCards(mini.seed, mini.answers), recent = mini.answers.slice(count % 2 ? -1 : -2);
  return <div className="life-panel-stack"><h3>{MINI_GAMES.find(m => m.id === id)?.name}</h3>{id === 'memory' ? <><p>配对 {matched.size / 2}/6 · 翻牌 {count} 次</p><div className="life-memory-grid">{board.map((v, i) => <button aria-label={`翻开第 ${i + 1} 张${matched.has(i) ? '，已配对' : ''}`} disabled={matched.has(i) || count % 2 === 1 && recent.includes(i) || count > 0 && count % 2 === 0 && revealed} key={i} className={matched.has(i) ? 'matched' : ''} onClick={() => run(g => answerMiniGame(g, i))}>{matched.has(i) || recent.includes(i) && revealed ? ['🌿', '🌼', '🎵', '📚', '🌙', '☕'][v] : '?'}</button>)}</div></> : id === 'rhythm' ? <><p>第 {count + 1}/8 拍，标记位于中间绿色区域时点击。</p><div className="life-rhythm" role="img" aria-label="节拍标记在绿色区时点击"><span/><i style={{ left: `${now / 10}%` }}/></div><button className="primary-button" onClick={() => run(g => answerMiniGame(g, Math.round((performance.now() - beatStart.current) % 1000)))}>点击节拍 / 空格</button></> : <><span className="little-label">第 {count + 1}/5 题</span><h3>{question?.text}</h3><div className="life-quiz-options">{question?.options.map((text, i) => <button className="secondary-button" key={text} onClick={() => run(g => answerMiniGame(g, i))}>{text}<ArrowRight size={14}/></button>)}</div></>}<button className="text-button" onClick={() => run(abandonMiniGame)}>退出本次游戏</button></div>;
}
