import { LifeNews } from './LifeExchange';
import { useCallback, useEffect, useRef, useState, type Dispatch, type SetStateAction } from 'react';
import { motion, useDragControls, useMotionValue, useMotionValueEvent } from 'motion/react';
import { ArrowRight, CalendarDays, Compass, Heart, Leaf, MessageCircle, Newspaper, Minus, Plus, RotateCcw, Save, Settings2 } from 'lucide-react';
import Modal from './Modal';
import GameIcon from './GameIcon';
import { LifeFamily, LifeFinance, LifeHealth, LifeMiniGame, LifeOverview, LifeTasks, LifeWork, money, type LifeProps } from './LifePanels';
import { actionLock, advanceLife, chooseLife, inheritLife, lifeAction, lifeAge, lifeBusy, lifePartner, teleportLife, type LifeResult } from '../game/life';
import { createGame } from '../game/engine';
import { startMiniGame } from '../game/lifeGames';
import { CHARACTERS, PLACES, REGIONS, REGION_BY_ID, imagePath } from '../game/data';
import { JOBS, LIFE_ACTIONS, LIFE_ATLASES, LIFE_EVENTS, LIFE_REGIONS, type LifeRegion } from '../game/lifeData';
import { playerPortrait } from '../game/player';
import { asset } from '../utils/asset';
import { taskEdgePosition } from '../game/mapTasks';
import { mapDragBounds } from '../game/mapView';
import useMapTouch from '../hooks/useMapTouch';
import type { GameState, Panel, Scene } from '../game/types';
import type { LifePanel } from '../game/lifeTypes';
const LABELS: Record<LifePanel, string> = { news:'拾光新闻', overview: '人生与账本', atlas: '三张人生大地图', place: '区域小地图', work: '人才市场与工作', finance: '交易与资产', health: '身体与医院', family: '恋人与家庭', tasks: '人生长任务', journal: '人生手帐', game: '课表之外的小游戏', death: '人生终章', guide: '围墙之外的游玩指引' };
type Props = { game: GameState; setGame: Dispatch<SetStateAction<GameState>>; notify: (s: string) => void; open: (p: Panel) => void; blocked: boolean; saved: boolean; onSchoolScene: (s: Scene) => void; onSchoolPlace: (id: string) => void };
function LifeMap({ image, pins, onPin, portrait, companion, background=false, hud=false }: { image: string; pins: { id: string; x: number; y: number; name: string; ready?: boolean }[]; onPin: (id: string) => void; portrait: string; background?: boolean; hud?: boolean; companion?: { name: string; image: string } }) {
  const [zoom, setZoom] = useState(1.5), view = useRef<HTMLDivElement>(null), dragging = useRef(false), x = useMotionValue(0), y = useMotionValue(0), controls = useDragControls();
  const [art, setArt] = useState({ width: 1672, height: 941 });
  const [size, setSize] = useState({ width: 800, height: 450, layerWidth: 1672, layerHeight: 941 });
  const source = image.startsWith('/') ? image : asset(`images/${image}.webp`);
  useMapTouch({ viewport: view, dragging, zoom, setZoom, x, y, size });
  const [offset, setOffset] = useState({ x: 0, y: 0 });
  useMotionValueEvent(x, 'change', value => setOffset(p => ({ ...p, x: value })));
  useMotionValueEvent(y, 'change', value => setOffset(p => ({ ...p, y: value })));
  const edges = pins.filter(p => p.ready).flatMap(pin => { const point = { x: size.width / 2 + offset.x + (pin.x / 100 - .5) * art.width * zoom, y: size.height / 2 + offset.y + (pin.y / 100 - .5) * art.height * zoom }; const marker = taskEdgePosition(point, size); return marker ? [{ ...marker, pin }] : []; });
  const pinOffset=(pin:{x:number;y:number;name:string})=>{const sx=size.width/2+offset.x+(pin.x/100-.5)*art.width*zoom,sy=size.height/2+offset.y+(pin.y/100-.5)*art.height*zoom,half=50+pin.name.length*8.5;if(sx<0||sx>size.width)return 0;let center=Math.max(half+10,Math.min(size.width-half-10,sx));const hudRight=size.width<700?248:286,hudBottom=size.width<700?285:565;if(background&&hud&&sy>=70&&sy<=hudBottom&&center-half<hudRight)center=Math.min(size.width-half-10,Math.max(center,hudRight+half+12));return center-sx;};
  const bounds = mapDragBounds(size, { width: size.layerWidth, height: size.layerHeight }, zoom);
  useEffect(() => { const el = view.current; if (!el) return; const measure = () => setSize({ width: el.clientWidth, height: el.clientHeight, layerWidth: art.width, layerHeight: art.height }); const observer = new ResizeObserver(measure); observer.observe(el); measure(); return () => observer.disconnect(); }, [art.width, art.height]);
  useEffect(() => { x.set(Math.max(bounds.left, Math.min(bounds.right, x.get()))); y.set(Math.max(bounds.top, Math.min(bounds.bottom, y.get()))); }, [bounds.left, bounds.right, bounds.top, bounds.bottom, x, y]);
  useEffect(() => { setZoom(1.5); x.set(0); y.set(0); }, [image, x, y]);
  return <div className={`life-map-wrap ${background?'life-map-background':''}`}><div className="life-map-viewport" ref={view}><div className="cloud-sky" aria-hidden="true"/><motion.div className="life-map-layer" drag dragControls={controls} dragListener={false} dragConstraints={bounds} dragElastic={.02} dragMomentum={false} onPointerDown={e => { if (e.pointerType !== 'touch' && !(e.target as HTMLElement).closest('button')) controls.start(e); }} onDragStart={() => { dragging.current = true; }} onDragEnd={() => { setTimeout(() => { dragging.current = false; }, 150); }} style={{ x, y, scale: zoom, width: art.width, height: art.height, left: "50%", top: "50%", marginLeft: -art.width / 2, marginTop: -art.height / 2 }}><img src={source} alt="手绘人生地图" draggable={false} onLoad={e => { const img = e.currentTarget; setArt({ width: img.naturalWidth, height: img.naturalHeight }); }}/>{pins.map(pin => <button className="life-map-pin hotspot-sign" key={pin.id} style={{ left: `${pin.x}%`, top: `${pin.y}%`, transform:`translate(-50%,-50%) scale(${1/zoom}) translateX(${pinOffset(pin)}px)` }} onClick={() => { if (!dragging.current) onPin(pin.id); }} aria-label={`进入${pin.name}`}><MapLabel name={pin.name}/>{pin.ready && <b className="life-map-alert" aria-label="有可进行的行动">!</b>}</button>)}<div className="life-avatar"><img src={portrait} alt="你的头像"/></div>{companion && <div className="life-map-companion" aria-label={`${companion.name}正在同行`}><img src={imagePath(companion.image)} alt={companion.name}/><small>{companion.name}</small></div>}</motion.div>{background&&<div className="cloud-frame" aria-hidden="true"><img src={asset('images/cloud-frame.webp')} alt=""/></div>}<div className="life-map-edges" aria-label="屏幕外可进行的地点">{edges.map((edge, i) => <button key={edge.pin.id} className={`life-edge edge-${edge.edge}`} style={{ left: edge.x, top: Math.max(background?80:24, Math.min(size.height-(background?(size.width<700?122:75):24),edge.y+i*30)) }} title={edge.pin.name} aria-label={`屏幕外：${edge.pin.name}`} onClick={() => onPin(edge.pin.id)}><ArrowRight size={17} style={{ transform: `rotate(${edge.angle}deg)` }}/><b>!</b></button>)}</div></div><div className="life-map-toolbar"><span>原始资源 {art.width} × {art.height} · {Math.round(zoom * 100)}%</span><a href={source} target="_blank" rel="noreferrer">查看完整原图</a><div><button aria-label="缩小人生地图" onClick={() => setZoom(v => Math.max(1, v - .2))}><Minus size={17}/></button><button aria-label="恢复人生地图视角" onClick={() => { setZoom(1.5); x.set(0); y.set(0); }}><RotateCcw size={16}/></button><button aria-label="放大人生地图" onClick={() => setZoom(v => Math.min(3, v + .2))}><Plus size={17}/></button></div></div></div>;
}
function MapLabel({ name }: { name: string }) { return <><GameIcon name="leaf" size={28}/><strong>{name}</strong><ArrowRight size={14}/></>; }
export default function LifeDashboard({ game: g, setGame, notify, open, blocked, saved, onSchoolScene, onSchoolPlace }: Props) {
  const guideKey = `shiguang-life-guide:${g.name}:${g.life.generation}`;
  const [panel, setPanel] = useState<LifePanel | null>(() => { try { return g.life.weeks === 0 && !localStorage.getItem(guideKey) ? 'guide' : null; } catch { return g.life.weeks === 0 ? 'guide' : null; } }), [guidePage, setGuidePage] = useState(0), [location, setLocation] = useState(''),[financeSection,setFinanceSection]=useState('crypto'),[hud,setHud]=useState(()=>window.innerWidth>700);
  const l = g.life, region = LIFE_REGIONS.find(r => r.id === l.region) ?? LIFE_REGIONS[0], atlas = LIFE_ATLASES.find(a => a.id === l.atlas)!, partner = lifePartner(g);
  const effective: LifePanel | null = l.death && !l.death.settled ? 'death' : l.body.emergency ? 'health' : l.game ? 'game' : panel;
  const activeModal = !!effective || !!l.pending;
  const currentGame = useRef(g); currentGame.current = g;
  const run = useCallback((op: (g: GameState) => LifeResult) => { const r = op(currentGame.current); currentGame.current = r.game; setGame(r.game); if (r.error || r.message) notify(r.error ?? r.message); }, [setGame, notify]);
  const show = (p: LifePanel) => setPanel(p);
  const finishGuide = () => { try { localStorage.setItem(guideKey, 'read'); } catch { /* The save export remains available when storage is full. */ } setPanel(null); };
  const props: LifeProps = { game: g, run, show };
  function visitRegion(r: LifeRegion) { run(g => teleportLife(g, r.atlas, r.id)); setLocation(''); setPanel(null); }
  const available = l.actions < 3 && !lifeBusy(g);
  const school = l.atlas === 'school', selectedPlaces = school ? PLACES.filter(p => p.scene === g.world.scene).map(p => ({ id: p.id, name: p.name, x: p.x, y: p.y, ready: false })) : region.places.map((p, i) => ({ id: String(i), name: p.name, x: [35, 56, 44, 68][i], y: [34, 48, 64, 74][i], ready: p.action?available&&!actionLock(g,p.action):p.game?available&&!l.used.includes('game:'+p.game):false }));
  function enterPlace(id:string){const p=region.places[Number(id)];if(!p)return;setLocation(p.name);if(p.panel){if(p.panel==='finance')setFinanceSection(Number(id)===0?'stocks':Number(id)===2?'amm':'crypto');show(p.panel);}else if(p.game){run(g=>startMiniGame(g,p.game!));if(available)show('game');}else show('place');}
  const sceneArt = school ? imagePath(g.world.scene) : asset(`images/${region.image}.webp`);
  const currentImage = school ? g.world.scene : region.image;
  let content;
  if (effective === 'overview') content = <LifeOverview {...props}/>;
  else if (effective === 'work') content = <LifeWork {...props}/>;
  else if (effective === 'finance') content = <LifeFinance {...props} section={financeSection}/>;
  else if(effective==='news')content=<LifeNews game={g} onMarket={()=>show('finance')}/>;
  else if (effective === 'health') content = <LifeHealth {...props}/>;
  else if (effective === 'family') content = <LifeFamily {...props}/>;
  else if (effective === 'tasks') content = <LifeTasks {...props}/>;
  else if (effective === 'game') content = <LifeMiniGame {...props}/>;
  else if (effective === 'atlas') content = <div className="life-panel-stack"><div className="life-atlas-tabs">{LIFE_ATLASES.map(a => <button key={a.id} className={l.atlas === a.id ? 'active' : ''} aria-pressed={l.atlas === a.id} disabled={lifeAge(g)<18&&a.id!=='school'} onClick={() => run(g => teleportLife(g, a.id))}>{a.name}大地图</button>)}</div><p>大学阶段即开放大学与社会。高中随时可回去；免费传送不会重置行动或年龄。</p><LifeMap image={atlas.image} portrait={playerPortrait(g)} companion={partner && l.family.following ? CHARACTERS[partner] : undefined} pins={school ? REGIONS : LIFE_REGIONS.filter(r => r.atlas === l.atlas).map(r => ({ ...r, ready: available }))} onPin={id => { if (school) { onSchoolScene(id as Scene); setPanel(null); } else visitRegion(LIFE_REGIONS.find(r => r.id === id)!); }}/><div className="life-card-grid">{school ? REGIONS.map(r => <button className="life-paper life-atlas-card" key={r.id} onClick={() => { onSchoolScene(r.id); setPanel(null); }}><img src={imagePath(r.id)} alt=""/><strong>{r.name}</strong><p>{r.subtitle}</p></button>) : LIFE_REGIONS.filter(r => r.atlas === l.atlas).map(r => <button className="life-paper life-atlas-card" key={r.id} onClick={() => visitRegion(r)}><img src={asset(`images/${r.image}.webp`)} alt="" loading="lazy"/><strong>{r.name}</strong><p>{r.description}</p><span>{r.places.length} 个小地点 <ArrowRight size={13}/></span></button>)}</div></div>;
  else if (effective === 'place') content = <div className="life-panel-stack"><img className="life-region-banner" src={sceneArt} alt="区域场景"/><p>{school ? '高中时间已经归档。你可以阅读旧故事，在这里休息、运动或与老朋友相处。' : region.description}</p><div className="life-button-row"><button className="text-button" onClick={() => show('atlas')}>返回三张大地图 <ArrowRight size={14}/></button><span>本周剩余 {3 - l.actions} 次行动</span></div>{location && <h3>{location}</h3>}<div className="life-card-grid">{(school ? [{name:'在高中认真上课',action:'course'},{ name: '在旧校园休息', action: 'rest' }, { name: '操场运动', action: 'exercise' }, { name: '约老朋友见面', action: 'social' }] : region.places.filter(p=>!location||p.name===location)).map((p, i) => { const lock = p.action ? actionLock(g, p.action) : null; return <article key={i} className="life-paper"><h3>{p.name}</h3>{p.action ? <><p>{LIFE_ACTIONS[p.action].hint}</p><button className="secondary-button" disabled={!!lock} onClick={() => run(g => lifeAction(g, p.action!))}>开始 · 1 行动{LIFE_ACTIONS[p.action].price ? ` · ¥${LIFE_ACTIONS[p.action].price}` : ''}</button><small className="life-lock">{lock ?? `体力 ${LIFE_ACTIONS[p.action].energy > 0 ? '+' : ''}${LIFE_ACTIONS[p.action].energy}`}</small></> : p.game ? <><p>交互小游戏，每周一次。</p><button className="secondary-button" disabled={!available || l.used.includes(`game:${p.game}`)} onClick={() => { run(g => startMiniGame(g, p.game!)); show('game'); }}>进入 · 1 行动</button></> : <button className="secondary-button" onClick={() => p.panel && show(p.panel)}>查看详情 <ArrowRight size={14}/></button>}</article>; })}</div></div>;
  else if (effective === 'journal') content = <div className="life-panel-stack">{!!l.ancestors.length && <article className="life-paper"><h3>上一代留下的名字</h3>{l.ancestors.map(a => <p key={a.generation}>{a.name} · {a.age.toFixed(1)} 岁 · {a.cause}</p>)}</article>}{l.memories.map((m, i) => <article className="life-paper" key={i}><span className="little-label">第 {m.week + 1} 周</span><h3>{m.title}</h3><p>{m.text}</p></article>)}</div>;
  else if (effective === 'death') content = <div className="life-panel-stack life-death"><GameIcon name="journal" size={65}/><h3>{g.name} · {l.death?.age.toFixed(1)} 岁</h3><p>{l.death?.cause}</p><p>第 {l.generation} 代，共走过 {l.weeks} 周，工作 {l.work.hours} 小时，留下 {l.memories.length} 段近期记录。</p><p>现金与资产扣除欠款后 ¥{money(Math.max(0, g.stats.money + portfolioValueSafe(g) - l.economy.debt))}。</p><div className="life-button-row"><button className="primary-button" onClick={() => { setGame(g => ({ ...g, life: { ...g.life, death: g.life.death ? { ...g.life.death, settled: true } : null } })); setPanel('journal'); }}>结算并阅读人生手帐</button><button className="secondary-button" onClick={() => open('saves')}>导出这段人生</button></div>{!!l.family.children.length && <><h3>继续孩子的人生</h3><p>未到高中时跳至15岁；已经上高中或成年则保持当前年龄，学位按照实际学习记录。新世代不继承上一代伴侣关系。</p>{l.family.children.map(c => <button className="secondary-button" key={c.id} onClick={() => { run(g => inheritLife(g, c.id, createGame())); setPanel(null); }}>{c.name} · 当前 {Math.max(0, (l.weeks - c.bornWeek) / 52).toFixed(1)} 岁 <ArrowRight size={14}/></button>)}</>}</div>;
  else if (effective === 'guide') { const pages = [ ['三个世界，一条时间线', l.stage==='school'?'先完成下一代高中阶段，18岁后开放大学与社会。高中学分需要每周学习积累。':'大学和社会同时开放，高中可以随时回去。大地图选区域，区域小地图选地点。传送不消耗行动，课程、工作、娱乐和检查会消耗。'], ['每周只抓住三件重要的事', '大学课程每周一次，至少 208 周与 160 学分取得本科。剩余时间安排技能、休息和兼职。结束本周会结算年龄、账单和行情。'], ['先面试，再找到自己的工作', '人才市场先看学历和技能，再看本周互动面试成绩。签约后需要每周完成排班才领工资。体力不足先休息，连续缺勤会结束合同。'], ['现金、风险与生活储备', '账本记录所有收入与支出。股票、现货、逐仓合约和 Uniswap 池都是模拟。保证金不是可用现金，利润没有承诺。别拿生活费冒险。'], ['认真听见身体，也认真维护关系', '高中习惯持续影响身体，周初会提示症状。检查发现线索，进一步检查确认。急救不因钱少而关闭。交往、求婚、孕育都需要双方同意。'], ['这一代与下一代', '长期任务跨周推进。孩子成长与照护一起计入日程；死亡后可结算，或继续孩子的人生。自动存档会保存人生阶段，清理浏览器前请导出。'] ]; content = <div className="life-guide"><span className="little-label">{guidePage + 1} / {pages.length}</span><h3>{pages[guidePage][0]}</h3><p>{pages[guidePage][1]}</p><div className="life-button-row"><button className="secondary-button" disabled={!guidePage} onClick={() => setGuidePage(p => p - 1)}>上一步</button><button className="primary-button" onClick={() => guidePage < pages.length - 1 ? setGuidePage(p => p + 1) : finishGuide()}>{guidePage < pages.length - 1 ? '下一步' : '开始安排我的人生'} <ArrowRight size={15}/></button><button className="text-button" onClick={finishGuide}>稍后再读</button></div></div>; }
  const event = LIFE_EVENTS.find(e => e.id === l.pending), pendingTitle = l.pending?.startsWith('confess:') ? '认真说出的心意' : l.pending==='school-transition'?'高中结束，下一步怎样走？':l.pending === 'proposal' ? '我们都愿意，把生活放在一起吗？' : l.pending === 'baby-plan' || l.pending === 'care-plan' ? '共同照护的新计划' : l.pending === 'separate' ? '认真谈一谈分别' : event?.title;
  return <div className="life-app"><div className="life-shell" inert={activeModal || blocked}><header className="life-header"><button className="life-brand" onClick={() => open('menu')}><GameIcon name="school" size={43}/><span>只要学不死<strong>就往死里学</strong></span></button><div className="life-identity"><img src={playerPortrait(g)} alt=""/><span><strong>{g.name}</strong><small>{lifeAge(g).toFixed(1)} 岁 · {l.stage==='school'?'新世代高中':l.stage === 'university' ? '大学人生' : '社会人生'} · 第 {l.generation} 代</small></span></div><div className="life-header-stats"><button onClick={() => show('health')}>体力 <b>{g.stats.energy.toFixed(0)}</b> · 压力 <b>{g.stats.stress.toFixed(0)}</b></button><button onClick={() => show('overview')}>现金 <b>¥{money(g.stats.money)}</b></button><button aria-label="设置" onClick={() => open('settings')}><Settings2 size={18}/></button></div></header>
    <main className="life-main life-world"><LifeMap background hud={hud} image={school?sceneArt:currentImage} portrait={playerPortrait(g)} companion={partner&&l.family.following?CHARACTERS[partner]:undefined} pins={selectedPlaces} onPin={school?(id=>l.stage==='school'?(setLocation(''),show('place')):onSchoolPlace(id)):enterPlace}/>
    <div className="life-world-heading"><button className="primary-button life-atlas-entry" onClick={()=>show('atlas')}><Compass size={18}/>大地图<ArrowRight size={14}/></button><button className="life-region-chip" onClick={()=>{setLocation('');show('place');}}>{atlas.name} · {school?REGION_BY_ID[g.world.scene].name:region.name}<ArrowRight size={14}/></button><button className="life-hud-toggle" aria-expanded={hud} onClick={()=>setHud(v=>!v)}>本周安排 {hud?'收起':'展开'}</button></div>
    {hud&&<div className="life-home-grid"><article className="life-paper"><span className="little-label">第 {l.weeks+1} 周 · 剩余 {3-l.actions} 次行动</span><h3>{l.stage==='school'?'新世代高中':l.education.degree?'学位之后，仍在生活':l.education.enrolled?l.education.school:'自己的下一步'}</h3><p>{l.education.enrolled&&!l.education.degree?l.education.credits+' 学分 · 课程每周一次':l.work.retired?'按缴费记录领取模拟收入':l.work.job?JOBS.find(j=>j.id===l.work.job)?.name+' · '+(l.used.includes('work')?'已完成排班':'尚未上班'):'先面试，再投递工作'}</p><button className="text-button" onClick={()=>show('tasks')}>任务手帐 <ArrowRight size={14}/></button><button className="text-button" onClick={()=>show('overview')}>本周账本 <ArrowRight size={14}/></button></article><article className="life-paper"><span className="little-label">{partner?'彼此的生活':'身体的声音'}</span><h3>{partner?'和'+CHARACTERS[partner].name+'慢慢相处':'听见身体'}</h3><p>{l.body.notices[0]??'身体、工作与家庭都需要留出一点时间。'}</p><button className="text-button" onClick={()=>show(partner?'family':'health')}>查看近况 <ArrowRight size={14}/></button></article></div>}
    <button className="life-news-preview" onClick={()=>show('news')}><span><Newspaper size={15}/>本周新闻</span><strong>{l.finance.news[0]?.title??'新闻正在整理'}</strong><ArrowRight size={14}/></button></main>
    <footer className="life-footer"><nav aria-label="人生导航">{(['atlas', 'overview', 'work', 'finance', 'health', 'family', 'tasks', 'news', 'game', 'journal'] as LifePanel[]).map(p => <button key={p} onClick={() => show(p)}>{p === 'atlas' ? <Compass size={17}/> : p === 'family' ? <Heart size={17}/> : <Leaf size={15}/>}<span>{LABELS[p].replace('三张人生', '').replace('课表之外的', '')}</span></button>)}<button onClick={() => open('messages')}><MessageCircle size={17}/><span>通讯</span></button><button onClick={() => open('saves')}><Save size={17}/><span>存档</span></button><button onClick={() => show('guide')}><GameIcon name="book" size={19}/><span>指引</span></button></nav><div className="life-week-row"><small>{saved ? '本地自动存档已保存' : '自动存档失败，请导出'} · v{import.meta.env.APP_VERSION}</small><span>本周行动 <b>{l.actions}/3</b></span><button className="primary-button" disabled={!!lifeBusy(g)} onClick={() => run(advanceLife)}><CalendarDays size={17}/>结束本周 <ArrowRight size={15}/></button></div><span className="creator-credit">Created by 小喵喵</span></footer></div>
    {!blocked && l.pending && <Modal title={pendingTitle ?? '人生里的选择'} onClose={() => {}} closeable={false} className="life-modal"><div className="life-choice"><p>{event?.text ?? (l.pending === 'proposal' ? '你们坐下来讨论婚姻、住房、经济和各自的边界。对方认真回应：愿意一起生活，也愿意继续彼此尊重。' : l.pending?.startsWith('confess:') ? `${CHARACTERS[l.pending.slice(8) as keyof typeof CHARACTERS]?.name}听完后回答：我也愿意和你交往。我们都认真确认这份心意，好吗？` : l.pending === 'separate' ? '一起讨论关系结束后的财务、照护与边界。可以分开，也可以先继续沟通。' : '双方都可以选择暂缓。确认后记录共同照护责任；私人过程略过。')}<span className="life-choice-note">此处不会消耗额外行动，也不会自动替你确认。</span></p><div className="life-quiz-options">{(l.pending==='school-transition'?['进入大学，开始积累学分','选择职业路径']:event?.choices ?? ['双方确认，继续', '先暂缓，保持当前生活']).map((text, i) => <button className={i === 0 ? 'primary-button' : 'secondary-button'} key={text} onClick={() => run(g => chooseLife(g, i))}>{text}</button>)}</div></div></Modal>}
    {!blocked && !l.pending && effective && <Modal title={LABELS[effective]} subtitle={`第 ${l.weeks + 1} 周 · ${lifeAge(g).toFixed(1)} 岁 · 剩余 ${3 - l.actions} 次行动`} className={`life-modal ${effective==='finance'?'exchange-modal':''}`} closeable={!l.body.emergency && !l.game && !(l.death && !l.death.settled)} onClose={() => setPanel(null)}>{content}</Modal>}
  </div>;
}
function portfolioValueSafe(g: GameState) { const f = g.life.finance; return Object.entries(f.holdings).reduce((n, [id, amount]) => n + amount * f.prices[id], 0) + f.positions.reduce((n, p) => n + Math.max(0, p.margin + (f.prices[p.asset] - p.entry) * p.quantity * (p.side === 'long' ? 1 : -1) - p.funding), 0) + f.pool.shares / f.pool.supply * (f.pool.eth * f.prices.ETH + f.pool.cash); }
