import { useState } from 'react';
import { ArrowUpRight, Newspaper } from 'lucide-react';
import { ASSETS } from '../game/lifeData';
import { aggregateCandles } from '../game/lifeFinance';
import type { GameState } from '../game/types';
import type { Candle } from '../game/lifeTypes';
const fmt=(n:number)=>n.toLocaleString('zh-CN',{maximumFractionDigits:2});
export function marketDate(g:GameState,day:number){return new Date(Date.UTC(2025,8,1)+(g.life.originWeek*7+day)*86400000).toISOString().slice(0,10);}
export function LifeNews({game:g,onMarket}:{game:GameState;onMarket?:()=>void}){
 const [category,setCategory]=useState('全部');
 return <div className="life-panel-stack"><p className="life-disclaimer">游戏内虚构新闻，每两周更新。影响行情预期、租金及新签合同报价；不是实时报道或投资建议。</p><div className="paper-tabs life-tabs">{['全部','经济','教育','医疗','劳动','市场'].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>{g.life.finance.news.filter(n=>category==='全部'||n.category===category).map(n=><article key={n.id} className="life-paper news-story"><span className="little-label">{n.category} · {marketDate(g,n.week*7)} · 拾光虚构通讯社</span><h3>{n.title}</h3><p>{n.text}</p><div className="news-impact">{Object.entries(n.impacts).map(([id,v])=><span key={id}>{ASSETS.find(a=>a.id===id)?.name} · {v>=0?'改善':'承压'}预期</span>)}{n.rent!==0&&<span>周租金调整 {(n.rent*100).toFixed(1)}%</span>}{n.wages!==0&&<span>新合同报价 {(n.wages*100).toFixed(1)}%</span>}</div><small>市场预期持续 {n.duration} 周，随机冲击可能抵消或反转方向。旧合同报价保持签约时水平。</small>{onMarket&&<button className="text-button" onClick={onMarket}>查看市场反应 <ArrowUpRight size={14}/></button>}</article>)}</div>;
}
function moving(candles:Candle[],period:number){return candles.map((_,i)=>i<period-1?null:candles.slice(i-period+1,i+1).reduce((n,c)=>n+c.close,0)/period);}
export function ExchangeMarket({game:g,asset,onAsset,onNews}:{game:GameState;asset:string;onAsset:(id:string)=>void;onNews:()=>void}){
 const [period,setPeriod]=useState(1),[hover,setHover]=useState<number|null>(null);
 const f=g.life.finance,all=aggregateCandles(f.candles[asset],period),data=all.slice(-48),start=all.length-data.length,ma5=moving(all,5).slice(start),ma20=moving(all,20).slice(start);
 const min=Math.min(...data.map(c=>c.low)),max=Math.max(...data.map(c=>c.high)),pad=(max-min)*.09||max*.03,low=min-pad,high=max+pad;
 const px=(i:number)=>42+(i+.5)/data.length*690,py=(p:number)=>24+(high-p)/(high-low)*235,width=Math.max(2,690/data.length*.62),volumeMax=Math.max(...data.map(c=>c.volume),1);
 const selected=data[hover??data.length-1],last=data[data.length-1],change=(last.close/last.open-1)*100;
 const points=(values:(number|null)[])=>values.flatMap((v,i)=>v===null?[]:[px(i)+','+py(v)]).join(' ');
 const quote=f.prices[asset],related=f.news.filter(n=>asset in n.impacts).slice(0,4);
 return <div className="exchange-market"><aside className="exchange-watch"><span className="little-label">自选行情</span>{ASSETS.map(a=>{const c=f.candles[a.id].at(-1)!,v=(c.close/c.open-1)*100;return <button key={a.id} aria-pressed={asset===a.id} className={asset===a.id?'active':''} onClick={()=>{onAsset(a.id);setHover(null);}}><strong>{a.name}</strong><span>{fmt(f.prices[a.id])}</span><small className={v>=0?'market-up':'market-down'}>{v>=0?'+':''}{v.toFixed(2)}%</small></button>;})}<small>本地模拟 · CNY计价<br/>休市与24小时行情统一为游戏日。</small></aside>
 <section className="exchange-chart"><div className="exchange-quote"><div><strong>{ASSETS.find(a=>a.id===asset)?.name}</strong><b>¥{fmt(quote)}</b><span className={change>=0?'market-up':'market-down'}>{change>=0?'+':''}{change.toFixed(2)}%</span></div><div className="exchange-period">{[[1,'日线'],[7,'周线'],[28,'四周线']].map(([days,label])=><button key={days} aria-pressed={period===days} className={period===days?'active':''} onClick={()=>{setPeriod(Number(days));setHover(null);}}>{label}</button>)}</div></div>
 <div className="exchange-ohlc"><span>{marketDate(g,selected.day)}</span><span>开 {fmt(selected.open)}</span><span>高 {fmt(selected.high)}</span><span>低 {fmt(selected.low)}</span><span>收 {fmt(selected.close)}</span><span>量 {fmt(selected.volume)}</span></div>
 <svg className="candlestick-chart" viewBox="0 0 800 365" role="img" tabIndex={0} aria-label={asset+'模拟K线，方向键查看蜡烛数据'} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setHover(i=>Math.max(0,Math.min(data.length-1,(i??data.length-1)+(e.key==='ArrowLeft'?-1:1))));}}} onPointerMove={e=>{const box=e.currentTarget.getBoundingClientRect(),i=Math.floor(((e.clientX-box.left)/box.width*800-42)/690*data.length);setHover(Math.max(0,Math.min(data.length-1,i)));}} onPointerLeave={()=>setHover(null)}>
 {[0,1,2,3,4].map(i=><g key={i}><line x1="42" x2="735" y1={24+i*235/4} y2={24+i*235/4} className="chart-grid"/><text x="740" y={28+i*235/4}>{fmt(high-i*(high-low)/4)}</text></g>)}
 {data.map((c,i)=><g key={c.day} className={c.close>=c.open?'candle-up':'candle-down'}><title>{marketDate(g,c.day)+' 开 '+c.open+' 高 '+c.high+' 低 '+c.low+' 收 '+c.close}</title><line x1={px(i)} x2={px(i)} y1={py(c.high)} y2={py(c.low)}/><rect x={px(i)-width/2} y={Math.min(py(c.open),py(c.close))} width={width} height={Math.max(1,Math.abs(py(c.open)-py(c.close)))}/><rect x={px(i)-width/2} y={329-c.volume/volumeMax*53} width={width} height={c.volume/volumeMax*53} opacity=".5"/>{!!c.news.length&&<circle cx={px(i)} cy="270" r="4" className="chart-news"><title>{c.news.map(id=>f.news.find(n=>n.id===id)?.title??'历史新闻').join('；')}</title></circle>}</g>)}
 <polyline points={points(ma5)} className="ma-five"/><polyline points={points(ma20)} className="ma-twenty"/>
 {hover!==null&&<g className="chart-crosshair"><line x1={px(hover)} x2={px(hover)} y1="20" y2="330"/><line x1="42" x2="735" y1={py(selected.close)} y2={py(selected.close)}/></g>}
 {[0,Math.floor(data.length/2),data.length-1].map(i=><text key={i} x={px(i)} y="351" textAnchor="middle">{marketDate(g,data[i].day).slice(5)}</text>)}
 </svg><div className="chart-legend"><span>MA5</span><span>MA20</span><span>● 新闻发布后的首根K线</span><small>OHLC与成交量由虚拟市场生成，新闻影响预期，成交不代表真实订单簿。</small>{f.rebuiltBefore!==null&&<small>旧档在第 {Math.ceil(f.rebuiltBefore/7)+1} 周前只有周收盘价：历史日线为插值重建，不含成交量记录；旧现货成本按升级时价格建立基线。</small>}</div>
 </section><aside className="exchange-news"><button onClick={onNews}><Newspaper size={16}/>市场新闻 <ArrowUpRight size={14}/></button>{related.map(n=><article key={n.id}><small>{marketDate(g,n.week*7)} · {n.category}</small><strong>{n.title}</strong><p>{n.text}</p></article>)}{!related.length&&<p>本期暂无此资产相关报道，仍存在独立价格波动。</p>}<div className="exchange-depth"><strong>模拟深度参考</strong>{[3,2,1].map(i=><div key={i} className="market-down"><span>卖{i}</span><span>{fmt(quote*(1+i*.001))}</span><span>{(800/i/quote).toFixed(4)}</span></div>)}<hr/>{[1,2,3].map(i=><div key={i} className="market-up"><span>买{i}</span><span>{fmt(quote*(1-i*.001))}</span><span>{(750/i/quote).toFixed(4)}</span></div>)}<small>参考展示，非真实挂单；当前交易按模拟标记价格成交。</small></div></aside></div>;
}
