import { useState, type Dispatch, type SetStateAction } from 'react';
import { ArrowRight, Heart, MapPin, MessageCircle, ShieldCheck } from 'lucide-react';
import { CHARACTERS, FAVORITE_GIFTS, ITEMS, PLACES, ROMANCE_IDS, imagePath } from '../game/data';
import { ADULT_BIRTHDAYS, matureAllowed } from '../game/audience';
import { characterLocation } from '../game/characterSchedule';
import { ROMANCE_SCENES } from '../game/romanceData';
import { beginRomanceScene, changeRelationship, confessionLock, endHomeVisit, makeHandmadeGift, sceneLock, setCompanion, updateBoundary } from '../game/romance';
import { bondStage } from '../game/social';
import { playerText } from '../game/player';
import { asset } from '../utils/asset';
import type { Audience, GameState, RomanceId } from '../game/types';

interface Props { game: GameState; setGame: Dispatch<SetStateAction<GameState>>; audience: Audience; initialContact?: RomanceId; onGift: (id: RomanceId, item: string) => void; onChat: (id: RomanceId) => void; onVisit: (id: string) => void; onQuests: () => void; notify: (text: string) => void }
const OPERATIONS = [['walk', '一起散步', '1 行动'], ['date', '安排约会', '1 行动'], ['home', '邀请回家做客', '1 行动'], ['hand', '牵手', '本周一次亲近'], ['hug', '抱一会儿', '本周一次亲近'], ['kiss', '轻吻', '本周一次亲近'], ['talk', '认真沟通', '1 行动']] as const;
export default function RomancePanel({ game, setGame, audience, initialContact, onGift, onChat, onVisit, onQuests, notify }: Props) {
  const [id, setId] = useState<RomanceId>(initialContact ?? game.social.partner ?? 'su');
  const [tab, setTab] = useState<'us' | 'spend' | 'boundaries' | 'memories'>('us');
  const [gift, setGift] = useState(FAVORITE_GIFTS[id]);
  const [confirm, setConfirm] = useState<'cooling' | 'breakup' | null>(null);
  const character = CHARACTERS[id], bond = game.social.bonds[id], detail = game.romance.bonds[id];
  const dating = game.social.partner === id;
  const location = characterLocation(game, id);
  const memories = game.romance.memories.filter(memory => memory.character === id && (matureAllowed(game, audience) || !memory.id.startsWith('private:')));
  const confession = confessionLock(game, id);
  function commit(result: { game: GameState; error?: string }, message = '这份相处已自动保存。') { if (result.error) { notify(result.error); return; } setGame(result.game); setConfirm(null); notify(message); }
  function scene(sceneId: string) { commit(beginRomanceScene(game, id, sceneId, audience)); }
  return <div className="romance-panel">
    <div className="love-contact-tabs" aria-label="选择攻略对象">{ROMANCE_IDS.map(contact => <button key={contact} aria-pressed={id === contact} className={id === contact ? 'active' : ''} onClick={() => { setId(contact); setGift(FAVORITE_GIFTS[contact]); setConfirm(null); }}><img src={imagePath(CHARACTERS[contact].image)} alt=""/><span>{CHARACTERS[contact].name}</span>{game.social.partner === contact && <Heart size={12}/>}</button>)}</div>
    <div className="love-profile"><img src={imagePath(character.image)} alt={character.name}/><div><span className="little-label">我们的故事 · {bondStage(game, id)}</span><h3>{character.name}</h3><p>18 岁起 · 生日 {ADULT_BIRTHDAYS[id]} · 虚构成年角色</p><small>{dating ? `第 ${detail.sinceWeek + 1} 周确认交往 · 一起走过 ${Math.max(0, game.week - detail.sinceWeek)} 周` : detail.status === 'broken' ? '分开后的回忆也被认真保留' : '主动表白，让彼此清楚知道心意'}</small></div></div>
    <div className="love-bond-values"><span>信任 <b>{bond.trust}</b></span><span>心动 <b>{bond.affection}</b></span><span>了解 <b>{bond.understanding}</b></span><span>相处 <b>{detail.meetWeeks.length}</b> 周</span></div>
    <div className="paper-tabs love-tabs" role="tablist" aria-label="恋爱界面">{([['us', '我们'], ['spend', '相处'], ['boundaries', '约定'], ['memories', '回忆']] as const).map(([value, label]) => <button role="tab" key={value} aria-selected={tab === value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}</div>
    {tab === 'us' && <div className="love-overview">
      <p>{character.description}</p><blockquote>“{character.quote}”</blockquote>
      {!dating && <div className="love-confession"><h4>{detail.status === 'broken' ? '重新开始，需要重新答应' : '把喜欢认真说出口'}</h4><p>信任 60、心动 55、了解 30；至少在两个不同游戏周见面，并完成一次专属约见或心事回复。表白后仍可选择放慢节奏。</p><button className="primary-button" disabled={!!confession} onClick={() => scene('confess')}><Heart size={15}/>{detail.status === 'broken' ? '重新表白' : '主动表白'}</button><small className="love-lock">{confession ?? '对方也已表达心动，可以认真提出交往。'}</small>{detail.status === 'broken' && <button className="secondary-button" disabled={!!sceneLock(game, id, 'talk', audience)} onClick={() => scene('talk')}>分开后认真沟通 · 1 行动</button>}</div>}
      <div className="love-links"><button className="secondary-button" onClick={() => onChat(id)}><MessageCircle size={15}/>主动发消息</button>{location && <button className="secondary-button" onClick={() => onVisit(location.placeId)}><MapPin size={15}/>{location.following ? '正在与你同行' : `去${PLACES.find(place => place.id === location.placeId)?.name}`}</button>}{dating && <button className="secondary-button" onClick={onQuests}>恋爱专属长期任务 <ArrowRight size={14}/></button>}</div>
      {dating && <><div className="love-story-list"><h4>只属于你们的六段故事</h4><p>每段之间至少经过一周。地点、选择和进度会自动保存。</p>{ROMANCE_SCENES.filter(story => story.character === id).map(story => { const lock = sceneLock(game, id, story.id, audience); const done = memories.some(memory => memory.id.startsWith(`${story.id}:`)); return <button key={story.id} disabled={!!lock} onClick={() => scene(story.id)}><span><strong>{story.stage + 1}. {story.title}</strong><small>{done ? '已收进回忆' : lock ?? `${PLACES.find(place => place.id === story.placeId)?.name} · 1 行动`}</small></span><ArrowRight size={16}/></button>; })}</div></>}
    </div>}
    {tab === 'spend' && <div className="love-spend"><img className="love-art" src={asset(id === 'zhou' || id === 'xinghe' ? 'images/romance-men-moments.webp' : 'images/romance-moments.webp')} alt="成年情侣牵手、拥抱与轻吻的水彩插画"/><p className="panel-tip">本周剩余 {3 - game.actions} 次行动。散步、约会、来访和沟通各消耗 1 次；亲近以双方愿意为前提，每周记录一次。</p>{dating ? <><div className="love-operations">{OPERATIONS.map(([operation, label, cost]) => { const lock = sceneLock(game, id, operation, audience); return <button className="secondary-button" key={operation} disabled={!!lock} onClick={() => scene(operation)}><strong>{label}</strong><small>{lock ?? cost}</small></button>; })}<button className="secondary-button" disabled={detail.status !== 'normal'} onClick={() => commit(setCompanion(game, id, game.romance.escort !== id), game.romance.escort === id ? '已经结束同行。' : '恋人会在小地图上与你同行，周末各自回家。')}><strong>{game.romance.escort === id ? '结束同行' : '邀请同行 · 跟随'}</strong><small>不消耗行动 · 跨地图一起走</small></button></div>{game.romance.visitor === id && <div className="love-home-visit"><h4>{character.name}正在家里做客</h4><p>可以读书、听音乐和一起吃饭。离开时间由双方约定。</p><button className="secondary-button" onClick={() => { setGame(endHomeVisit(game)); notify('已经送对方回家。'); }}>结束来访，送对方回家</button>{matureAllowed(game, audience) && <button className="secondary-button mature-entry" disabled={!!sceneLock(game, id, 'private', audience)} onClick={() => scene('private')}><strong>私人时光 · 18+</strong><small>{sceneLock(game, id, 'private', audience) ?? '先看 NSFW 内容提示，可直接跳过'}</small></button>}</div>}</> : <p className="love-lock">确认交往后解锁恋人相处。仍可在通讯中约见、交流和送礼。</p>}
      <div className="love-gifts"><h4>把心意放进小礼物</h4><label>选择礼物<select value={gift} onChange={event => setGift(event.target.value)}>{ITEMS.map(item => <option key={item.id} value={item.id}>{item.name} × {game.inventory[item.id]}</option>)}</select></label><button className="primary-button" disabled={!game.inventory[gift] || bond.lastGiftWeek === game.week || !!game.pendingEvent} onClick={() => onGift(id, gift)}>送给{character.name} · 不消耗行动</button><p>每位同龄角色每周收一次礼物，喜欢的礼物会有不同回应。</p>{dating && <div className="handmade-progress"><strong>亲手制作的纪念册</strong><p>{detail.handmade ? detail.handmade.gifted ? '已经送出，心意留在聊天记录中。' : `已投入 ${detail.handmade.weeks.length}/3 个不同游戏周，每次制作消耗 1 次行动。` : '先用一份学长的笔记作为材料开始，再在三个不同游戏周制作。'}</p><button className="secondary-button" disabled={!!detail.handmade?.gifted || detail.handmade?.weeks.includes(game.week)} onClick={() => commit(makeHandmadeGift(game, id))}>{!detail.handmade ? '开始准备 · 1 份笔记材料' : detail.handmade.weeks.length < 3 ? '制作本周的一页 · 1 行动' : '送出亲手做的纪念册'}</button></div>}</div>
    </div>}
    {tab === 'boundaries' && <div className="love-boundaries"><p><ShieldCheck size={16}/>喜欢与边界可以同时存在。冷静期保留恋爱关系，分手会结束同行与来访。</p>{dating && <>{([['publicAffection', '在学校公开表达亲近', '会增加老师关注与同学议论，后续可以沟通。'], ['homeVisits', '愿意到家里做客', '每次来访仍需明确邀请，随时可以结束。'], ['touch', '愿意牵手、拥抱等亲近', '每次剧情都会再次确认，对方可以改变主意。']] as const).map(([key, label, description]) => <label className="love-boundary" key={key}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={detail.boundaries[key]} onChange={event => commit(updateBoundary(game, id, key, event.target.checked), '你们共同确认了新的相处边界。')}/></label>)}<div className="love-attention">{(['school', 'family', 'rumor'] as const).map((key, index) => <span key={key}>{['老师关注', '家人担心', '同学议论'][index]}<b>{game.romance.attention[key] < 35 ? '平静' : game.romance.attention[key] < 65 ? '需要留意' : '适合沟通'}</b></span>)}</div><p className="fine-print">关注会随时间下降；家人和老师的信任提供支持。一次关心剧情至少间隔两周，普通友情互动不增加恋爱关注。</p><div className="button-row"><button className="secondary-button" onClick={() => setConfirm('cooling')}>暂时冷静</button><button className="text-button" onClick={() => setConfirm('breakup')}>认真提出分手</button></div>{confirm && <div className="love-confirm" role="alert"><h4>{confirm === 'breakup' ? '确定结束这段恋爱关系？' : '给彼此一段冷静的时间？'}</h4><p>{confirm === 'breakup' ? '共同回忆与任务进度保留，恋爱专属任务暂停；旧约见取消。以后重新开始，需要沟通和新的明确答应。' : '暂停同行与亲近，可以在相处页认真沟通，再决定是否恢复。'}</p><div className="button-row"><button className="secondary-button" onClick={() => setConfirm(null)}>再想一想</button><button className="primary-button" onClick={() => commit(changeRelationship(game, id, confirm), confirm === 'breakup' ? '你们好好说了再见，共同回忆会保留。' : '已经约定暂时冷静，准备好时再沟通。')}>确定{confirm === 'breakup' ? '分手' : '冷静'}</button></div></div>}</>}{!dating && <p>交往后，可以共同约定相处边界。</p>}</div>}
    {tab === 'memories' && <div className="love-memories">{!memories.length ? <p>认真相处过的片刻会留在这里。</p> : [...memories].reverse().map(memory => <article key={memory.id}><span className="little-label">第 {memory.week + 1} 周{memory.skipped ? ' · 已跳过私密描写' : ''}</span><h4>{memory.title}</h4><p>{playerText(game, memory.result)}</p></article>)}</div>}
  </div>;
}
