import { createRequire } from 'node:module';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
const require = createRequire(resolve('.poster-tools/package.json'));
const QRCode = require('qrcode');
const target = 'https://shiguang-campus-life.pages.dev/';
const fontPath = resolve('node_modules/@fontsource/zcool-kuaile/index.css');
const fonts = readFileSync(fontPath, 'utf8').replace(/url\(([^)]+)\)/g, (_, path) => `url(data:font/woff2;base64,${readFileSync(resolve(dirname(fontPath), path.replace(/["']/g, ''))).toString('base64')})`);
const art = readFileSync('docs/poster/poster-art.png').toString('base64');
const qr = await QRCode.toString(target, { type: 'svg', errorCorrectionLevel: 'H', margin: 4, color: { dark: '#33452a', light: '#ffffff' } });
writeFileSync('docs/poster/game-link-qr.svg', qr);
const html = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>只要学不死 就往死里学 · 海报</title><style>
${fonts}
*{box-sizing:border-box}body{margin:0;background:#f6efd9;color:#746247;font-family:'ZCOOL KuaiLe',sans-serif}.poster{position:relative;width:1200px;height:1800px;overflow:hidden;background:#f9f2dd}.art{position:absolute;width:100%;height:100%;object-fit:cover}.paper{position:absolute;inset:0;background:linear-gradient(180deg,#fbf5e522%,transparent 28%,transparent 74%,#faf3e6aa 88%,#faf3e6dd)}.frame{position:absolute;inset:30px;border:2px solid #a8b08488;border-radius:22px}.title{position:absolute;top:76px;left:65px;right:65px;text-align:center}.eyebrow{font-size:26px;letter-spacing:9px;color:#9b8b66}.title h1{margin:20px 0 0;font-size:112px;line-height:1.15;letter-spacing:7px;color:#756448;text-shadow:3px 4px #fff9e9}.title h1 span{color:#73875b}.features{position:absolute;left:83px;bottom:390px;display:flex;gap:18px}.features span{border:1px solid #a9b18a;background:#fff9e5c9;border-radius:32px;padding:14px 24px;font-size:27px;color:#78835d}.invite{position:absolute;left:86px;bottom:135px;width:660px}.invite h2{font-size:36px;line-height:1.4;color:#697e51;margin:0 0 12px}.invite p{font-size:24px;line-height:1.5;margin:0;color:#887a59}.scan{margin-top:18px!important;font-size:30px!important;color:#6f8056!important}.domain{font-family:Georgia,serif;font-size:24px!important;letter-spacing:.3px;margin-top:12px!important}.qr{position:absolute;right:84px;bottom:125px;width:272px;padding:8px;background:#fff;border:1px solid #bbb18c;border-radius:15px;box-shadow:0 5px 0 #b6ba9388}.qr svg{display:block;width:254px;height:254px;shape-rendering:crispEdges}.qr-caption{position:absolute;right:80px;bottom:80px;width:280px;text-align:center;font-size:24px;color:#7e865f}.small{position:absolute;bottom:47px;left:85px;font-size:19px;letter-spacing:2px;color:#9a9775}
</style><div class="poster"><img class="art" src="data:image/png;base64,${art}" alt="苏晓与同学走在温暖的西安校园"><div class="paper"></div><div class="frame"></div><div class="title"><div class="eyebrow">西安 · 高三生存物语</div><h1>只要学不死<br><span>就往死里学</span></h1></div><div class="features"><span>9 张探索地图</span><span>11 个长期任务</span><span>友情与恋爱</span></div><div class="invite"><h2>你的高三，不止一种答案。</h2><p>把故事写进手帐，把心意发给同桌。<br>在四十个游戏周里，慢慢长大。</p><p class="scan">扫一扫，开启你的校园故事</p><p class="domain">shiguang-campus-life.pages.dev</p></div><a class="qr" href="${target}" aria-label="扫码打开只要学不死，就往死里学">${qr}</a><div class="qr-caption">即开即玩 · 自动存档</div><div class="small">原创校园养成游戏 / 即开即玩</div></div></html>`;
writeFileSync('docs/poster/shiguang-poster.html',html);
console.log(JSON.stringify({ html: resolve('docs/poster/shiguang-poster.html'), target }));
